### ISSUE TITLE
default-scheduler  running Reserve plugin "DynamicResources": waiting for resource driver to allocate resource

### ISSUE THREAD

**Issue by reprogrammer** [kubernetes-sigs/dra-example-driver#34] opened 2023-09-19 20:11 UTC
The resources don't get allocated to the pods. The pods report that they are waiting for the resource driver to allocate resources.

```
$ kubectl apply --filename=gpu-test1.yaml
namespace/gpu-test1 created
resourceclaimtemplate.resource.k8s.io/gpu.example.com created
pod/pod0 created
pod/pod1 created
```
```
$ kubectl -n gpu-test1 describe pod pod0
Name:             pod0
Namespace:        gpu-test1
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=pod
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Containers:
  ctr0:
    Image:      ubuntu:22.04
    Port:       <none>
    Host Port:  <none>
    Command:
      bash
      -c
    Args:
      export; sleep 9999
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-whf4d (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-whf4d:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  4m6s (x19 over 89m)  default-scheduler  running Reserve plugin "DynamicResources": waiting for resource driver to allocate resource
```

```
$ kubectl get pods -A
NAMESPACE            NAME                                                               READY   STATUS    RESTARTS   AGE
dra-example-driver   dra-example-driver-controller-85f975c557-8r7bh                     1/1     Running   0          90m
dra-example-driver   dra-example-driver-kubeletplugin-8n82d                             1/1     Running   0          90m
gpu-test1            pod0                                                               0/1     Pending   0          89m
gpu-test1            pod1                                                               0/1     Pending   0          89m
kube-system          coredns-5d78c9869d-dtwh8                                           1/1     Running   0          3h31m
kube-system          coredns-5d78c9869d-xlwqt                                           1/1     Running   0          3h31m
kube-system          etcd-dra-example-driver-cluster-control-plane                      1/1     Running   0          3h31m
kube-system          kindnet-fhg7h                                                      1/1     Running   0          3h31m
kube-system          kindnet-s7xf4                                                      1/1     Running   0          3h31m
kube-system          kube-apiserver-dra-example-driver-cluster-control-plane            1/1     Running   0          3h31m
kube-system          kube-controller-manager-dra-example-driver-cluster-control-plane   1/1     Running   0          3h31m
kube-system          kube-proxy-4tsmq                                                   1/1     Running   0          3h31m
kube-system          kube-proxy-xtgzr                                                   1/1     Running   0          3h31m
kube-system          kube-scheduler-dra-example-driver-cluster-control-plane            1/1     Running   0          3h31m
local-path-storage   local-path-provisioner-7dbf974f64-xc6gz                            1/1     Running   0          3h31m
```
```
$ kubectl describe -n dra-example-driver nas dra-example-driver-cluster-worker
Name:         dra-example-driver-cluster-worker
Namespace:    dra-example-driver
Labels:       <none>
Annotations:  <none>
API Version:  nas.gpu.resource.example.com/v1alpha1
Kind:         NodeAllocationState
Metadata:
  Creation Timestamp:  2023-09-19T17:35:53Z
  Generation:          9
  Managed Fields:
    API Version:  nas.gpu.resource.example.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .:
          k:{"uid":"78b31856-7709-4b6e-9c6e-d41b6a288a98"}:
      f:spec:
    Manager:      set-nas-status
    Operation:    Update
    Time:         2023-09-19T18:34:59Z
    API Version:  nas.gpu.resource.example.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:allocatableDevices:
      f:status:
    Manager:    dra-example-kubeletplugin
    Operation:  Update
    Time:       2023-09-19T18:35:03Z
  Owner References:
    API Version:     v1
    Kind:            Node
    Name:            dra-example-driver-cluster-worker
    UID:             78b31856-7709-4b6e-9c6e-d41b6a288a98
  Resource Version:  10984
  UID:               364485dd-e3f9-4ee2-b981-b1cebba9ef4b
Spec:
  Allocatable Devices:
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-657bd2e7-f5c2-a7f2-fbaa-0d1cdc32f81b
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-18db0e85-99e9-c746-8531-ffeb86328b39
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-93d37703-997c-c46f-a531-755e3e0dc2ac
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-ee3e4b55-fcda-44b8-0605-64b7a9967744
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-9ede7e32-5825-a11b-fa3d-bab6d47e0243
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-e7b42cb1-4fd8-91b2-bc77-352a0c1f5747
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-f11773a1-5bfb-e48b-3d98-1beb5baaf08e
    Gpu:
      Product Name:  LATEST-GPU-MODEL
      Uuid:          GPU-0159f35e-99ee-b2b5-74f1-9d18df3f22ac
Status:              Ready
Events:              <none>
```
```
$ kubectl -n dra-example-driver logs dra-example-driver-controller-85f975c557-8r7bh 
I0919 18:34:53.630764       1 controller.go:322] "resource controller: Starting" driver="gpu.resource.example.com"
E0919 18:35:58.143409       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod0\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod0"
E0919 18:35:58.149436       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod1\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod1"
E0919 18:35:58.150599       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod0\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod0"
E0919 18:35:58.156355       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod1\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod1"
E0919 18:35:58.161759       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod0\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod0"
E0919 18:35:58.342806       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod1\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod1"
E0919 18:35:58.543318       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod0\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod0"
E0919 18:35:58.943520       1 controller.go:372] "resource controller: processing failed" err="pod claim gpu: pod \"gpu-test1/pod1\": ResourceClaim not created yet" key="schedulingCtx:gpu-test1/pod1"
```

```
$ kubectl -n dra-example-driver logs dra-example-driver-kubeletplugin-8n82d 
Defaulted container "plugin" out of: plugin, init (init)
I0919 18:35:03.239203       1 draplugin.go:220] "registering drapbv1alpha3.NodeServer"
I0919 18:35:03.239245       1 nonblockinggrpcserver.go:105] "dra: GRPC server started"
I0919 18:35:03.239320       1 nonblockinggrpcserver.go:105] "registrar: GRPC server started"
I0919 18:35:03.952446       1 nonblockinggrpcserver.go:116] "registrar: handling request" requestID=1 request="&InfoRequest{}"
I0919 18:35:03.952473       1 nonblockinggrpcserver.go:127] "registrar: handling request succeeded" requestID=1 response="&PluginInfo{Type:DRAPlugin,Name:gpu.resource.example.com,Endpoint:/var/lib/kubelet/plugins/gpu.resource.example.com/plugin.sock,SupportedVersions:[1.0.0],}"
I0919 18:35:03.952789       1 nonblockinggrpcserver.go:116] "registrar: handling request" requestID=2 request="&RegistrationStatus{PluginRegistered:true,Error:,}"
I0919 18:35:03.952799       1 nonblockinggrpcserver.go:127] "registrar: handling request succeeded" requestID=2 response="&RegistrationStatusResponse{}"
```

**Comment by klueska** [comment] 2023-09-19 20:25
It looks like https://github.com/kubernetes-sigs/dra-example-driver/pull/24 and https://github.com/kubernetes-sigs/dra-example-driver/pull/25 were merged without updating the kind image to Kubernetes 1.28 (which these API changes require).

@byako, @pohly How were these PRs tested? I know we need to improve our automation, but at a minimum, we must always ensure that the workflow outlined in the README works for any PR that we merge.

**Comment by klueska** [comment] 2023-09-19 20:51
I have reproduced the issue on the existing setup and verified that upgrading to kubernetes 1.28.1 resolves the issue. I will open a PR in the morning.

**Comment by klueska** [comment] 2023-09-19 21:30
Went ahead and opened the pull request now:
https://github.com/kubernetes-sigs/dra-example-driver/pull/35

**Comment by reprogrammer** [comment] 2023-09-20 00:24
Yes, @klueska I confirmed that using v1.28.0 fixes this issue:

```
diff --git a/demo/scripts/common.sh b/demo/scripts/common.sh
index 69011d1..d17f7b2 100644
--- a/demo/scripts/common.sh
+++ b/demo/scripts/common.sh
@@ -20,7 +20,8 @@
 # Usage: kind-build-image.sh <tag of generated image>
 
 # A reference to the current directory where this script is located
-SCRIPTS_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
+#SCRIPTS_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
+SCRIPTS_DIR="scripts"
 
 # The name of the example driver 
 : ${DRIVER_NAME:=dra-example-driver}
@@ -33,7 +34,8 @@ SCRIPTS_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
 
 # The kubernetes tag to build the kind cluster from
 # From https://github.com/kubernetes/kubernetes/tags
-: ${KIND_K8S_TAG:="v1.27.1"}
+#: ${KIND_K8S_TAG:="v1.27.1"}
+: ${KIND_K8S_TAG:="v1.28.0"}
 
 # The name of the kind cluster to create
 : ${KIND_CLUSTER_NAME:="${DRIVER_NAME}-cluster"}
@@ -45,7 +47,7 @@ SCRIPTS_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
 : ${DRIVER_IMAGE:="${DRIVER_IMAGE_REGISTRY}/${DRIVER_IMAGE_NAME}:${DRIVER_IMAGE_TAG}"}
 
 # The derived name of the kind image to build
-: ${KIND_IMAGE_BASE_TAG:="v20230515-01914134-containerd_v1.7.1"}
-: ${KIND_IMAGE_BASE:="gcr.io/k8s-staging-kind/base:${KIND_IMAGE_BASE_TAG}"}
-: ${KIND_IMAGE:="kindest/node:${KIND_K8S_TAG}-${KIND_IMAGE_BASE_TAG}"}
-
+# : ${KIND_IMAGE_BASE_TAG:="v20230515-01914134-containerd_v1.7.1"}
+# : ${KIND_IMAGE_BASE:="gcr.io/k8s-staging-kind/base:${KIND_IMAGE_BASE_TAG}"}
+# : ${KIND_IMAGE:="kindest/node:${KIND_K8S_TAG}-${KIND_IMAGE_BASE_TAG}"}
+: ${KIND_IMAGE:="kindest/node:v1.28.0"}
```

**Comment by pohly** [comment] 2023-09-20 05:58
> How were these PRs tested?

I've not tested them manually, just reviewed them.

**Comment by byako** [comment] 2023-09-20 06:29
> It looks like #24 and #25 were merged without updating the kind image to Kubernetes 1.28 (which these API changes require).
> 
> @byako, @pohly How were these PRs tested? I know we need to improve our automation, but at a minimum, we must always ensure that the workflow outlined in the README works for any PR that we merge.

With real cluster, unfortunately, I did not check the Kind image, sorry about that.

**Comment by pohly** [comment] 2023-11-20 10:38
Is this resolved?

**Closed** 2024-04-18 12:19 UTC
Labels: lifecycle/rotten
